export const Colors = [
  { name: "Dark Soft Peach", hex: "#e5c4a6" },
  { name: "Dark Mint Cream", hex: "#dce5e1" },
  { name: "Dark Lavender Mist", hex: "#cfcfe1" },
  { name: "Dark Lemon Chiffon", hex: "#e5e1b8" },
  { name: "Dark Pale Turquoise", hex: "#9dd6d6" },
  { name: "Dark Misty Rose", hex: "#e5cdca" },
  { name: "Dark Honeydew", hex: "#d8e5d8" },
  { name: "Dark Alice Blue", hex: "#d8dfe5" },
  { name: "Dark Champagne", hex: "#decfb9" },
  { name: "Dark Powder Blue", hex: "#9ec9cf" },
  { name: "Dark Cornsilk", hex: "#e5dfc6" },
  { name: "Dark Pale Goldenrod", hex: "#d6d099" },
  { name: "Dark Light Cyan", hex: "#c9e5e5" },
  { name: "Dark Seashell", hex: "#e5dcd6" },
  { name: "Dark Wheat", hex: "#dcc7a1" },
  { name: "Dark Light Pink", hex: "#e5a3ad" },
  { name: "Dark Azure", hex: "#d8e5e5" },
  { name: "Dark Floral White", hex: "#e5e1d8" },
  { name: "Dark Pale Green", hex: "#88e188" },
  { name: "Dark Blanched Almond", hex: "#e5d3b8" },
];
